# Generated by Django 4.0.4 on 2022-04-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yazi',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
