# Generated by Django 4.0.4 on 2022-04-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_yazi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
