# Generated by Django 4.0.4 on 2022-04-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_yazi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='image',
            field=models.ImageField(upload_to='blog_images'),
        ),
        migrations.AlterField(
            model_name='yazi',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
